# Generated by Django 2.2.4 on 2019-08-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
