# Generated by Django 2.2.4 on 2019-08-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20190820_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='login',
            new_name='email',
        ),
    ]
