# Generated by Django 2.2.4 on 2019-08-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
